-- Delete the SAMPLE database tables

DROP TABLE SEQUENCE;

DROP TABLE BOOK_LIBRARYUSER;

DROP TABLE BOOKBORROW;
DROP TABLE BOOKITEM;
DROP TABLE PERIODICALITEM;
DROP TABLE PUBLICATIONITEM;

DROP TABLE BOOKORDER;

DROP TABLE BOOK;
DROP TABLE PERIODICAL;
DROP TABLE PUBLICATION;

DROP TABLE LIBRARYUSER;


