/*
 * MainFrame.java
 *
 * Created on 2008년 8월 6일 (수), 오후 1:13
 */

package lms.borrowandreturn.borrowandreturnsystem;

/**
 *
 * @author  chae
 */
public class MainFrame extends javax.swing.JFrame {
    
    Main main ;
    
    /** Creates new form MainFrame */
    public MainFrame(Main main) {
        this.main = main ;
        setTitle("자동 대출 반납 시스템") ;
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jUserIDTextField = new javax.swing.JTextField();
        jRegistrationNumberTextField = new javax.swing.JTextField();
        jBorrowButton = new javax.swing.JButton();
        jReturnButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jResultLabel = new javax.swing.JLabel();
        jCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("사용자ID:");

        jLabel2.setText("도서등록번호:");

        jBorrowButton.setText("도서 대출");
        jBorrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrowButtonActionPerformed(evt);
            }
        });

        jReturnButton.setText("도서 반납");
        jReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("결과:");

        jCloseButton.setText("종료");
        jCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBorrowButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jReturnButton)
                            .addGap(42, 42, 42))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jUserIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                        .addComponent(jRegistrationNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
                            .addGap(42, 42, 42))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCloseButton)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBorrowButton)
                    .addComponent(jReturnButton))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jUserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRegistrationNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCloseButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jBorrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrowButtonActionPerformed
// TODO add your handling code here:
    
    String userID = jUserIDTextField.getText() ;
    String registrationNumber = jRegistrationNumberTextField.getText() ;
    
    if ( userID.isEmpty() || registrationNumber.isEmpty() )
        jResultLabel.setText("사용자ID와 대출할 도서등록번호를 입력하세요 !") ;
    else {
        System.out.println("UnmannedBorrowReturnSI::BorrowButton: " + userID + "  " + registrationNumber ) ;
    
        String result = main.borrowHandler(userID, registrationNumber) ;
        jResultLabel.setText(result) ;
    }
        
}//GEN-LAST:event_jBorrowButtonActionPerformed

private void jReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnButtonActionPerformed
// TODO add your handling code here:
    
    //String userID = jUserIDTextField.getText() ;
    String registrationNumber = jRegistrationNumberTextField.getText() ;
    
    if ( registrationNumber.isEmpty() )
        jResultLabel.setText("반납할 도서등록번호를 입력하세요 !") ;
    else {
        System.out.println("UnmannedBorrowReturnSI::BorrowButton: " + registrationNumber ) ;    
        String result = main.returnHandler(registrationNumber) ;
        jResultLabel.setText(result) ;
    }
    
}//GEN-LAST:event_jReturnButtonActionPerformed

private void jCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseButtonActionPerformed
// TODO add your handling code here:
    
    System.exit(0);
}//GEN-LAST:event_jCloseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBorrowButton;
    private javax.swing.JButton jCloseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jRegistrationNumberTextField;
    private javax.swing.JLabel jResultLabel;
    private javax.swing.JButton jReturnButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jUserIDTextField;
    // End of variables declaration//GEN-END:variables

}
